### ISSUE TITLE
Not an issue but a question : what is a submission ?

### ISSUE THREAD

**Issue by JLBA** [heimrichhannot/contao-submissions#1]
Hi every one,

I've just discovered and installed this extension but, as screenshots are in german, I don't really understand what it is for ? What is exactly a submission ? 

Thanks for explanations.

**Comment by fatcrobat** [comment]
Hi there, 

submissions in most cases are user generated form-submissions. It was developed to replace efg in our projects, as we require DCA related submissions with their own database table. You can create submission archives (Database table: tl_submission_archive) and configure what part of tl_submission (fields) will be displayed and can be edited.

Try it together with [heimrichhannot/contao-submissions_creator](https://github.com/heimrichhannot/contao-submissions_creator), create a front end module (Submission-Reader), select the fields and a submission archive and add the module to your website.

If you need more input, feel free to ask.
